version: "3.9"
# Creates local network of waggles (peers)

x-common-variables: &common-variables
    BOOTSTRAP_ADDRS: /dns4/ix2oumqrtjaupt53l6cqpk6ct6iaa5guconwgtvgdk2v3i5wjiyehryd.onion/tcp/7788/ws/p2p/QmRbkBkhTt2DbLMF8kAaf1oxpfKQuEfLKFzVCDzQhabwkw
    DEBUG: libp2p:dht*,waggle:db*

services:
  entrynode:
    build: .
    environment:
        <<: *common-variables
        HIDDEN_SERVICE_SECRET: ED25519-V3:+OQSh718QNMfTV+jpsO1moEjSRVnHvPOlEhS1WKdGGkP0OPwMG0iXWx6FJ9liCsbhJGFwLg/I13v6qhB8KVv5Q==
        PEERID_FILE: localEntryNodePeerId.json
    volumes:
        - entrynode-data:/root/.zbay
  
  peer: &peer
    build: .
    environment: 
        <<: *common-variables
        HIDDEN_SERVICE_SECRET: null
        PEERID_FILE: ""
    command: ["ts-node", "src/entryNodeData.ts"]
      

  peer-extra:
    <<: *peer

volumes:
    entrynode-data:
